webapp/models.py
from datetime import datetime
from werkzeug.security import generate_password_hash, check_password_hash
from flask_login import UserMixin
from datetime import datetime

from webapp.extensions import db, login


class Projects(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    project_name = db.Column(db.String(50))
    tasks = db.relationship('Tasks',backref='project',lazy='dynamic')
    user_id = db.Column(db.Integer,db.ForeignKey('users.id'))


    def if_name_is_empty(self):
        if self.project_name == "":
            return True
        else:
            return False

    def if_name_is_valid(self):
        if self.project_name != self.project_name.capitalize():
            return False 
        else:
            return True


    def __repr__(self):
        return 'Project name - {}'.format(self.project_name)


class Tasks(db.Model):
    id = db.Column(db.Integer,primary_key=True)
    task_name = db.Column(db.String(50))
    task_status = db.Column(db.Boolean)
    task_priority = db.Column(db.Integer)
    date = db.Column(db.String(100)) 
    task_position = db.Column(db.Integer)
    project_id = db.Column(db.Integer,db.ForeignKey('projects.id'))

    def date_time_now(self):
        if self.date == datetime.utcnow():
            return True
        else:
            return False

    def __repr__(self):
        return 'Task name - {}'.format(self.task_name)



class Users(UserMixin,db.Model):
    id = db.Column(db.Integer,primary_key=True)
    username = db.Column(db.String(128), unique=True, nullable=False)
    password_hash = db.Column(db.String(256), nullable=False)
    projects = db.relationship('Projects',backref='author',lazy='dynamic')
    
    def set_password(self, password):
        self.password_hash = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password_hash, password)

    def __repr__(self):
        return str(self.id)

@login.user_loader
def load_user(id):
    return Users.query.get(int(id))
    

webapp/__init__.py
import os
import logging

from logging.handlers import RotatingFileHandler
from flask import Flask

from config import Config
from webapp.blueprints.main import main as main_blueprint
from webapp.blueprints.auth import auth as auth_blueprint
from webapp.extensions import db, migrate, login
from webapp import models

def create_app():
	app = Flask(__name__)
	app.config.from_object(Config)

	register_extensions(app)

	app.register_blueprint(main_blueprint)
	app.register_blueprint(auth_blueprint, url_prefix="/auth")

	register_make_shell_context(app)

	if app.config['LOG_TO_STDOUT']:
		stream_handler = logging.StreamHandler()
		stream_handler.setLevel(logging.INFO)
		app.logger.addHandler(stream_handler)
	else:
		if not os.path.exists('logs'):
			os.mkdir('logs')
		file_handler = RotatingFileHandler('logs/todo.log', maxBytes=10240, backupCount=10)
		file_handler.setFormatter(logging.Formatter('%(asctime)s %(levelname)s: %(message)s ''[in %(pathname)s:%(lineno)d]'))
		file_handler.setLevel(logging.INFO)
		app.logger.addHandler(file_handler)

	app.logger.setLevel(logging.INFO)
	app.logger.info('ToDo List')

	return app

def register_extensions(app):
	db.init_app(app)
	migrate.init_app(app, db=db)
	login.init_app(app)

def register_make_shell_context(app):
	@app.shell_context_processor
	def make_shell_context():
		return {'db': models.db, 'Users': models.Users, 'Tasks': models.Tasks, 'Projects':models.Projects}

webapp/blueprints/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views

webapp/blueprints/main/views.py
from flask import redirect,url_for,jsonify,request,flash,render_template
from flask_login import current_user, login_required
from . import main
from webapp.models import Projects,Tasks
from webapp.extensions import db
import ast


################################################################ HOME
@main.route('/')
@main.route('/index')
def index():
    if current_user.is_authenticated:
        proj = Projects.query.filter_by(user_id=current_user.id).all()
        task = Tasks.query.order_by(Tasks.task_position).all()
    else:
        return redirect(url_for('auth.login'))
    return render_template('index.html',title='Welcome',proj=proj,task=task)

@main.route('/account')
@login_required
def account():
    return render_template('account.html',title='ToDo')

################################################################# PROJECT

@main.route('/add_project',methods=['GET', 'POST'])
def add_project():	
    if request.method=='POST':
        if current_user.is_authenticated:
            proj = Projects(project_name=request.form['name'],user_id=current_user.id)
            db.session.add(proj)
            db.session.commit()
            flash('Project added - {}'.format(request.form['name']))
        else:
            return redirect(url_for('auth.login'))      	
    return redirect(url_for('main.index'))

@main.route('/delete_project',methods=['GET','POST'])
def delete_project():
    delete_id = request.form['id']
    taskToDelete = Tasks.query.filter_by(project_id=delete_id).delete()
    projToDelete = Projects.query.filter_by(id=delete_id).first()
    db.session.delete(projToDelete)
    db.session.commit()
    flash('Project deleted')
    return redirect(url_for('main.index'))

@main.route('/update_project',methods=['GET','POST'])
def update_project():
    update_id = request.form['id']
    project_name = request.form['project_name']
    print(project_name)
    projToUpdate = Projects.query.filter_by(id=update_id).first()
    projToUpdate.project_name = project_name
    db.session.add(projToUpdate)
    db.session.commit()
    flash('Project updated - {}'.format(project_name))
    return redirect(url_for('main.index'))

############################################################# TASKS

@main.route('/add_task/<id>',methods=['GET','POST'])
def add_task(id):
    if request.method=='POST':
        task = Tasks(task_name=request.form['task_name'],task_status=False,task_priority=request.form['task_priority'],date=request.form['task_date'],task_position=0,project_id=id)
        db.session.add(task)
        db.session.commit()
        flash('Task added - {}'.format(request.form['task_name']))
    return redirect(url_for('main.index'))

@main.route('/delete_task',methods=['GET','POST'])
def delete_task():
	delete_id = request.form['id']
	print(delete_id)
	taskToDelete = Tasks.query.get(delete_id)
	db.session.delete(taskToDelete)
	db.session.commit()
	flash('Task deleted')
	return redirect(url_for('main.index'))

@main.route('/update_task/<id>',methods=['GET','POST'])
def update_task(id):
    name = request.form['task_name']
    date = request.form['task_date']
    priority = request.form['task_priority']
    taskToUpdate = Tasks.query.filter_by(id=id).first()
    taskToUpdate.task_name = name
    taskToUpdate.date = date
    taskToUpdate.task_priority = priority

    db.session.add(taskToUpdate)
    db.session.commit()
    flash('Task updated - {}'.format(name))
    return redirect(url_for('main.index'))

################################################################### ADDITIONAL

@main.route('/task_done/<id>',methods=['GET','POST'])
def task_done(id):
    taskDone = Tasks.query.get(id)
    if taskDone.task_status:
        taskDone.task_status = False
        flash('Task start')
    else:
        taskDone.task_status = True
        flash('Task done')
    db.session.add(taskDone)
    db.session.commit()
    return redirect(url_for('main.index'))

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <meta name="viewport" content="width=device-width, initial-scale=1" charset="UTF-8">
    <title> ToDo List </title>
</head>
<body>
{% include 'header.html' %}
<div class="container">
    <div class="row">
        <div class="col md-12">
            {% with messages = get_flashed_messages() %}
                {% if messages %}
                    {% for message in messages %}
                        {% if 'deleted' in message %}
                            <div class="alert alert-danger alert-dismissable" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">x</span>
                                </button>
                                {{message}}
                            </div>
                        {% elif 'Wrong' in message %}
                            <div class="alert alert-danger alert-dismissable" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">x</span>
                                </button>
                                {{message}}
                            </div>
                        {% else %}
                            <div class="alert alert-success alert-dismissable" role="alert">
                                <button type="button" class="close" data-dismiss="alert" aria-label="close">
                                <span aria-hidden="true">x</span>
                                </button>
                                {{message}}
                            </div>
                        {% endif %}
                    {% endfor %}
                {% endif %}
            {% endwith %}
		</div>
	</div>
</div>
{% block content %} {% endblock %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js" integrity="sha512-bLT0Qm9VnAYZDflyKcBaQ2gg0hSYNQrJ8RilYldYQ1FxQYoCLtUjuuRuZo+fjqhx/qtq/1itJ0C2ejDxltZVFg==" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js" integrity="sha384-B4gt1jrGC7Jh4AgTPSdUtOBvfO8shuf57BaghqFfPlYxofvL8/KUEfYiJOMMV+rV" crossorigin="anonymous"></script>
</body>
</html>

webapp/templates/header.html
<div class="jumbotron p-3">
    <div class="well text-left">
        <h3><a href="{{ url_for('main.index') }}">Todo List</a></h3>
    </div>
    <div class="well text-right">
        {% if current_user.is_anonymous %}
        	<a type="button"  class="btn btn-success" href="{{ url_for('auth.login') }}">Login</a>
        	<a type="button"  class="btn btn-warning btn-xs" href="{{ url_for('auth.register') }}">Register</a>
        {% else %}
        	<h2>{{ current_user.username }}
        	<a type="button"  class="btn btn-danger btn-xs" href="{{ url_for('auth.logout') }}">Logout</a></h2>
        {% endif %} 
    </div>
</div>

webapp/templates/index.html
{% extends "base.html" %}
{% block content %}

<div class="container">
  <div class="row">
    <div class="col md-12">
      {% if current_user.is_anonymous %}
        <div class="alert alert-warning alert-dismissable" role="alert">
          <button type="button" class="close" data-dismiss="alert" aria-label="close"><span aria-hidden="true">x</span></button>
            <span>You are a guest. All guests have access to each other's projects and tasks. Please log in or register to create personal projects with tasks</span>
        </div>
      {% endif %}
      <div class="jumbotron p-3">
        <div class="text-center">
          <button type="button"  class="btn btn-success" data-toggle="modal" data-target="#mymodal-pr">Add New Project</button><br>
        </div>
      </div>

    		{% for pr in proj %}
    		<div class="jumbotron p-3">
          <h2>{{ pr.id }} - <b>{{ pr.project_name }}</b>
            <button type="button"  class="btn btn-danger btn-xs float-right" data-toggle="modal" data-target="#modaldelete-pr{{pr.id}}">Delete</button>
            <button type="button"  class="btn btn-warning btn-xs float-right" data-toggle="modal" data-target="#modaledit-pr{{pr.id}}">Edit Project</button>
    			<h2>Manage <b>Tasks </b>  <button type="button"  class="btn btn-success float-right" data-toggle="modal" data-target="#mymodal{{pr.id}}">Add New Task</button> </h2>
      
    			<table class="table table-hover table-dark">

            <tr>
                <th>ID</th>
                <th>Status</th>
                <th>Task</th>
                <th>Deadline</th>
                <th>Priority</th>
            </tr>

            {% for ts in task %}
            {% if ts.project_id == pr.id %}
              <tr>
                <td>{{ts.id}}</td>
                <td>{% if ts.task_status == False %}
                      <form class="form" action="{{ url_for('main.task_done',id=ts.id) }}" method="POST">     
                        <input type="hidden" value="{{ ts.id }}">
                        <button type="submit">+</button>
                      </form>
                    {% else %}
                      <form class="form" action="{{ url_for('main.task_done',id=ts.id) }}" method="POST">     
                        <input type="hidden" value="{{ ts.id }}">
                        <button type="submit">X</button>
                      </form> 
                    {% endif %}
                </td>
                <td>{{ts.task_name}}</td>
                <td>{{ts.date}}</td>
                <td>{{ts.task_priority}}</td>
                <td>
                <button type="button"  class="btn btn-danger btn-xs float-right" data-toggle="modal" data-target="#modaldelete{{ts.id}}">Delete</button>
                <button type="button"  class="btn btn-warning btn-xs float-right" data-toggle="modal" data-target="#modaledit{{ts.id}}">Edit</button>
                </td>
          	 </tr>

            {% endif %}

                  <!-- Modal Edit Task-->
<div id="modaledit{{ts.id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Update Information</h4>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('main.update_task',id=ts.id) }}" method="POST">
          <div class="form-group">
            <label>Task:</label>
            <input type="hidden"  name="id" value="{{ts.id}}">
            <input type="hidden"  name="task_status" value="{{ts.task_status}}">
            <input type="text" class="form-control" name="task_name" value="{{ts.task_name}}">
          </div>
          <div class="form-group">
            <label>Deadline:</label>
            <input type="date" class="form-control" name="task_date" value="{{ts.date}}">
          </div>
          <div class="form-group">
            <label>Priority:</label>
            <input type="number" class="form-control" name="task_priority" value="{{ts.task_priority}}">
          </div>
          <div class="form-group">
              <button class="btn btn-primary" type="submit">Update</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

                      <!-- Modal Delete Task-->
<div id="modaldelete{{ts.id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Task</h4>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('main.delete_task') }}" method="POST">
          <div class="form-group">
            <label>Task: "{{ts.task_name}}"</label>
            <input type="hidden"  name="id" value="{{ts.id}}">
          </div>
          <div class="form-group">
            <button class="btn btn-danger btn-xs" type="submit">Dlete</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

                        {% endfor %}
                		</table>
            </div>

                              <!-- Modal Add Task-->
<div id="mymodal{{pr.id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Add Task</h4>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('main.add_task',id=pr.id) }}" method="POST">
          <div class="form-group">
            <label>Task:</label>
            <input type="text" class="form-control" name="task_name" required="1">
          </div>
          <div class="form-group">
            <label>Deadline:</label>
            <input type="date" class="form-control" name="task_date" required="1">
          </div>
          <div class="form-group">
            <label>Priority:</label>
            <input type="number" class="form-control" name="task_priority" required="1">
          </div>
          <div class="form-group">
            <button class="btn btn-primary" type="submit">Add Task</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

                  <!-- Modal Edit Project-->
<div id="modaledit-pr{{pr.id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Update Information</h4>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('main.update_project') }}" method="POST">
          <div class="form-group">
            <label>Project:</label>
            <input type="hidden"  name="id" value="{{pr.id}}">
            <input type="text" class="form-control" name="project_name" value="{{pr.project_name}}">
          </div>
          <div class="form-group">
            <button class="btn btn-primary" type="submit">Update</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>


                      <!-- Modal Delete Project-->
<div id="modaldelete-pr{{pr.id}}" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Delete Project</h4>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('main.delete_project') }}" method="POST">
          <div class="form-group">
            <label>Project: "{{pr.project_name}}"</label>
            <input type="hidden"  name="id" value="{{pr.id}}">
          </div>
          <div class="form-group">
            <button class="btn btn-danger btn-xs" type="submit">Dlete</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

        {% endfor %}

                  <!-- Modal Add Project-->
<div id="mymodal-pr" class="modal fade" role="dialog">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h4 class="modal-title">Add Project</h4>
      </div>
      <div class="modal-body">
        <form action="{{ url_for('main.add_project') }}" method="POST">
          <div class="form-group">
            <label>Project:</label>
            <input type="text" class="form-control" name="name" required="1">
          </div>
          <div class="form-group">
              <button class="btn btn-primary" type="submit">Add Project</button>
          </div>
        </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

        </div>
    </div>
</div>

{% endblock %}

webapp/templates/login.html
{% extends "base.html" %}

{% block content %}
<div class="container">
 	<div class="row justify-content-center">
    	<div class="col-12 col-sm-6 col-md-3">
    		<div class="jumbotron p-3">
	    		<div class="form-container">
		    		<h1>Log In</h1>
		    		<form action="" method="post" novalidate>
		        		{{ form.hidden_tag() }}
		        		<p>
		            		{{ form.username.label }}<br>
		            		{{ form.username }}<br>
				            {% for error in form.username.errors %}
		    		        		<span style="color: red;">[{{ error }}]</span>
		            		{% endfor %}
		        		</p>
		        		<p>
		            		{{ form.password.label }}<br>
		            		{{ form.password }}<br>
		            		{% for error in form.password.errors %}
		            			<span style="color: red;">[{{ error }}]</span>
		            		{% endfor %}
		        		</p>
		        		<p>{{ form.remember_me() }} {{ form.remember_me.label }}</p>
		        		<p>{{ form.submit() }}</p>
		    		</form>
	    		</div>
	    	</div>
		</div> 
	</div> 
</div>
{% endblock %}

webapp/templates/register.html
{% extends "base.html" %}

{% block content %}
<div class="container">
 	<div class="row justify-content-center">
    	<div class="col-12 col-sm-6 col-md-3">
    		<div class="jumbotron p-3">
	    		<div class="form-container">
				    <h1>Register</h1>
				    <form action="" method="post">
				        {{ form.hidden_tag() }}
				        <p>
				            {{ form.username.label }}<br>
				            {{ form.username }}<br>
				            {% for error in form.username.errors %}
				            <span style="color: red;">[{{ error }}]</span>
				            {% endfor %}
				        </p>
				        <p>
				            {{ form.password.label }}<br>
				            {{ form.password }}<br>
				            {% for error in form.password.errors %}
				            <span style="color: red;">[{{ error }}]</span>
				            {% endfor %}
				        </p>
				        <p>
				            {{ form.password2.label }}<br>
				            {{ form.password2 }}<br>
				            {% for error in form.password2.errors %}
				            <span style="color: red;">[{{ error }}]</span>
				            {% endfor %}
				        </p>
				        <p>{{ form.submit() }}</p>
			    	</form>
	    		</div>
	    	</div>
		</div> 
	</div> 
</div>
{% endblock %}